# Program:  plot1
# Author:   Joseph Conklin
# Date:     February 2019

# Description:  This program fulfills one of the requirements
# of the Exploratory Data Analysis.  The project requires the
# creation of four plots of electric power consumption data
# from the downloaded file household_power_consumption.txt

# The source is an archive of electric power consumption data 
# residing at the UC Irvine Machine Learning Repository.  The
# plots generated by this program are stored as PNG files.

# Read in file of household power consumption data as
# all data as character so date and time variables
# can be segregated for combination later

electric_power_consumption_1 <- read.table("./household_power_consumption.txt",
                                         sep = ";",header = TRUE,na.strings = "?",
                                         colClasses=c(rep("character",9)))

# Retrieve date and time variables from household power consumption data

electric_power_consumption_1 <- electric_power_consumption_1[,1:2]

# Read in file of household power consumption data as
# so numeric variables can be segregated for combination later

electric_power_consumption_2 <- read.table("./household_power_consumption.txt",
                                           sep = ";",header = TRUE,na.strings = "?")

# Retrieve date and time variables from household power consumption data

electric_power_consumption_2 <- electric_power_consumption_2[,3:9] 

# Consolidate variables into single file

electric_power_consumption <- cbind(electric_power_consumption_1,
                                    electric_power_consumption_2)

# Delete files from global environment no longer needed

rm(electric_power_consumption_1,electric_power_consumption_2)

# Convert date variable by as.Date to facilitate later plotting

electric_power_consumption$Date <- as.Date(electric_power_consumption$Date,
                                           format=c("%d/%m/%Y"))

# Extract range of dates for plots

electric_power_consumption <- subset(electric_power_consumption,
                                     electric_power_consumption$Date >= "2007-02-01" &
                                     electric_power_consumption$Date <= "2007-02-02")

# Create first plot of histogram of global active power

hist(electric_power_consumption$Global_active_power,main="Global Active Power",
     xlab="Global Active Power (kilowatts)",col="red")

# Delete files from global environment no longer needed 

rm(list=ls())

